sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=3.2.4
sonar.sources=.
sonar.inclusions=app.py
sonar.exclusions=test_app.py,**/*.pyc
sonar.tests=.
sonar.test.inclusions=test_app.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3
sonar.host.url=http://host.docker.internal:9000